In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0,2.0,3.0,4.0],
              [8.0,5.0,4.0,6.0]])
print(b)

[[1. 2. 3. 4.]
 [8. 5. 4. 6.]]


In [4]:
#get dimension
a.ndim

1

In [5]:
#get shape
b.shape

(2, 4)

In [6]:
#get type
a.dtype

dtype('int32')

In [7]:
#size
a.itemsize

4

In [8]:
#get a total size
a.nbytes

12

In [9]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
#get a specific element
b[1,4]

12

In [11]:
#get a specific row
b[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
b[:,1]

array([2, 9])

In [13]:
b[0,1:-1:2]

array([2, 4, 6])

In [14]:
#change the element
b[1,5]=20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
b[:,2]=[1,2]
print(b)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3_d example

In [16]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#get a specific number
b[1,1,0]

7

In [18]:
#replace
b[1,1,1]=9
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


### INITIALIZING DIFFRENT TYPES OF ARRAY

In [19]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
#All 1s matrix
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
#Any other number(full)
np.full((3,3),99 )

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [22]:
#full_like
np.full_like(b,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [23]:
#random decimal numbers
np.random.rand(4,3,3)

array([[[0.98891118, 0.58029333, 0.57969163],
        [0.3771875 , 0.94990646, 0.65623854],
        [0.87160485, 0.98186283, 0.02528685]],

       [[0.0522019 , 0.86924403, 0.05136864],
        [0.86443182, 0.50791417, 0.19736488],
        [0.9039436 , 0.89093313, 0.52507515]],

       [[0.41044582, 0.56942211, 0.11465132],
        [0.83783177, 0.72638706, 0.68953722],
        [0.09050915, 0.90874117, 0.88485801]],

       [[0.9191343 , 0.90335649, 0.04475557],
        [0.94812604, 0.5466904 , 0.82303618],
        [0.1292976 , 0.78327611, 0.97330321]]])

In [24]:
# random integer value
np.random.randint(99,size=(3,3))

array([[38, 66, 83],
       [ 9, 78, 98],
       [69, 67, 59]])

In [25]:
# the identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#repeate an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4 ,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
# Build an array
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying an array

In [35]:
a=np.array([1,2,3])
b=a.copy()
b[0]=10
print(b)

[10  2  3]


## Mathamatics

In [36]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a+2

array([3, 4, 5, 6])

In [38]:
a-2

array([-1,  0,  1,  2])

In [39]:
a*2

array([2, 4, 6, 8])

In [40]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [42]:
a**2

array([ 1,  4,  9, 16])

In [41]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [43]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [52]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [56]:
# find the detrminent
c=np.identity(3)
np.linalg.det(c)

1.0

### statistics

In [61]:
stats=np.array([[1,2,3],[4,5,6]])
sats

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(stats)

1

np.max(stats)

In [66]:
np.min(stats ,axis=0)

array([1, 2, 3])

In [67]:
np.sum(stats)

21

## Reorganizing  an array

In [72]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### vertically stacking vectors or matrix

In [76]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
# horizontal stacking
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
### Load Data from File

In [94]:
filedata=np.genfromtxt('data.txt' , delimiter=',')
filedata=filedata.astype('int32')
filedata

array([12, 87, 45,  3, 76, 22, 91, 54, 18, 67, 29,  8, 73, 60, 41, 95, 14,
       33, 82,  6, 58, 27, 49, 90, 11, 64, 35,  2, 78, 53, 20, 86, 47,  9,
       71, 25, 62, 38,  5, 80, 16, 97, 44, 31, 69, 24, 56, 13, 84,  7])

### Boolean masking and Advance indexing

In [86]:
filedata[filedata >50]

array([87., 76., 91., 54., 67., 73., 60., 95., 82., 58., 90., 64., 78.,
       53., 86., 71., 62., 80., 97., 69., 56., 84.])

In [98]:
np.any(filedata>50,axis=0)

True

In [99]:
np.all(filedata>50,axis=0)

False

In [102]:
((filedata >50) & (filedata <90))

array([False,  True, False, False,  True, False, False,  True, False,
        True, False, False,  True,  True, False, False, False, False,
        True, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False])

In [114]:
#Create a NumPy array of numbers from 1 to 20.
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [119]:
print(a[0:5],a[-3:])

[1 2 3 4 5] [18 19 20]


In [121]:
a = np.array([12,87,45,3,76,22,91,54])
a[a>50]=0
print(a)

[12  0 45  3  0 22  0  0]


In [123]:
a=np.arange(1,13)
a=a.reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
np.mean(a)

1

In [127]:
np.min(a)

1

In [128]:
np.max(a)

12

In [144]:
a=np.random.randint(0,100,(20,60))
print(a[(a > 20) & (a < 60)])

[27 49 41 52 59 53 28 26 47 56 41 26 39 58 48 23 32 46 45 55 42 35 49 46
 38 28 42 28 22 54 36 46 27 50 33 40 32 38 44 26 46 36 25 27 41 27 40 27
 28 26 48 21 28 43 30 38 43 23 47 22 37 32 52 36 29 31 57 37 29 46 34 46
 26 41 43 33 53 35 37 51 39 25 34 26 47 34 49 51 54 45 23 58 40 56 55 40
 46 27 46 34 32 53 46 33 56 24 26 55 56 49 44 43 36 36 41 50 24 53 49 36
 24 30 54 35 59 51 31 58 31 25 29 29 43 26 25 51 25 56 52 36 29 41 53 26
 27 43 39 37 54 47 32 28 55 22 46 50 21 25 33 26 38 59 36 35 44 31 25 47
 41 31 40 33 26 22 32 42 44 28 31 57 24 40 26 43 30 27 48 31 56 24 24 37
 50 47 46 47 57 50 25 24 46 29 55 41 41 35 46 21 32 33 54 53 53 24 56 39
 38 37 24 26 21 25 34 53 26 41 40 45 58 55 59 25 23 59 50 38 44 59 56 35
 21 48 53 38 36 26 56 41 23 21 38 31 54 46 28 51 31 29 30 32 33 43 37 32
 45 43 28 48 25 52 32 40 32 31 56 52 37 47 52 23 55 50 30 46 30 58 27 30
 53 22 30 35 44 34 57 22 51 59 45 39 23 38 53 41 41 41 49 53 53 53 29 50
 46 23 26 42 59 54 52 57 33 35 58 48 35 50 54 49 38

In [148]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]
[10 26 42]
